### ISSUE TITLE
想换个https://www.toolnb.com 的友链

### ISSUE THREAD

**Issue by zhangjunjie6b** [jackapi/tools#1]
关键词:极客工具 
URL: https://www.geekstool.com/
望回复

**Comment by jackapi** [comment]
抱歉呀，目前只接受有备案和权重2以上的。

zhangjunjie6b ***@***.***> 于2023年4月17日周一 11:25写道：

**Comment by zhangjunjie6b** [comment]
那等我权二了再去备个案了再来   :-(
